# Generated by Django 3.2 on 2022-07-27 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Район доставки',
                'verbose_name_plural': 'Райони доставки',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('address', models.CharField(max_length=400, verbose_name='Вулиця, будинок')),
                ('amount', models.IntegerField(null=True, verbose_name='Вартість замовлення')),
                ('invoice_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ідентифікатор рахунку')),
                ('details', models.TextField(verbose_name='Деталі')),
                ('comment_client', models.TextField(blank=True, verbose_name='Коментар від клієнта')),
                ('is_working', models.BooleanField(default=False, verbose_name='Взято в роботу')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('rejected', models.BooleanField(default=False, verbose_name='Відхилено')),
                ('comment_agent', models.TextField(blank=True, verbose_name='Коментар від агента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата зміни')),
                ('districts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.districts', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
    ]
