# Generated by Django 3.2 on 2022-08-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='self_pickup',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Самовивіз'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_agent',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='UserAgent'),
        ),
    ]
