# Generated by Django 3.2 on 2022-08-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20220813_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='self_pickup',
            field=models.BooleanField(blank=True, default=False, verbose_name='Самовивіз'),
        ),
    ]
