# Generated by Django 3.2 on 2022-07-10 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmountProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значення')),
                ('price', models.IntegerField(verbose_name='Ціна')),
            ],
            options={
                'verbose_name': 'Кількість',
                'verbose_name_plural': 'Кількості',
            },
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Категорія')),
                ('image', models.ImageField(upload_to='categories/', verbose_name='Зображення')),
                ('slug', models.SlugField(max_length=200, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='SizeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значення')),
                ('price', models.IntegerField(verbose_name='Ціна')),
            ],
            options={
                'verbose_name': 'Розмір',
                'verbose_name_plural': 'Розміри',
            },
        ),
        migrations.CreateModel(
            name='VolumeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значення')),
                ('price', models.IntegerField(verbose_name='Ціна')),
            ],
            options={
                'verbose_name': "Об'єм",
                'verbose_name_plural': "Об'єми",
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('price', models.IntegerField(verbose_name='Ціна')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Картинка')),
                ('amount', models.ManyToManyField(blank=True, to='products.AmountProduct', verbose_name='Кількість')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.categoryproduct', verbose_name='Категорія')),
                ('size', models.ManyToManyField(blank=True, to='products.SizeProduct', verbose_name='Розмір')),
                ('volume', models.ManyToManyField(blank=True, to='products.VolumeProduct', verbose_name="Об'єм")),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
            },
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Ціна')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Комбо меню',
                'verbose_name_plural': 'Комбо меню',
            },
        ),
        migrations.CreateModel(
            name='CategoryCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.categoryproduct', verbose_name='Комбо категорії')),
            ],
            options={
                'verbose_name': 'Комбо категорія',
                'verbose_name_plural': 'Комбо категорії',
            },
        ),
    ]
