# Generated by Django 3.2 on 2022-08-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_categorycombo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='products/mobile', verbose_name='Картинка для mobile'),
        ),
    ]
