# Generated by Django 3.2 on 2022-07-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Адреса')),
                ('link', models.CharField(max_length=500, verbose_name='Лінк на google map')),
            ],
            options={
                'verbose_name': 'Адреса',
                'verbose_name_plural': 'Адреси',
            },
        ),
        migrations.CreateModel(
            name='CategorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(blank=True, max_length=100, verbose_name='Верхній заголовок')),
                ('title', models.CharField(max_length=200, verbose_name='Головний заголовок')),
                ('sub_title', models.TextField(blank=True, verbose_name='Під заголовок')),
            ],
            options={
                'verbose_name': 'Сторінка категорій',
                'verbose_name_plural': 'Сторінка категорій',
            },
        ),
        migrations.CreateModel(
            name='ComboSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(blank=True, max_length=100, verbose_name='Верхній заголовок')),
                ('title', models.CharField(max_length=200, verbose_name='Головний заголовок')),
                ('sub_title', models.TextField(blank=True, verbose_name='Під заголовок')),
            ],
            options={
                'verbose_name': 'Сторінка комбо',
                'verbose_name_plural': 'Сторінка комбо',
            },
        ),
        migrations.CreateModel(
            name='InfoCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_link', models.CharField(blank=True, max_length=400, verbose_name='Інстаграм (лінк)')),
                ('tiktok_link', models.CharField(blank=True, max_length=400, verbose_name='Тік-ток (лінк)')),
                ('facebook_link', models.CharField(blank=True, max_length=400, verbose_name='Фейсбук (лінк)')),
                ('logo_image', models.FileField(upload_to='logo/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Загальна інформація',
                'verbose_name_plural': 'Загальна інформація',
            },
        ),
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(blank=True, max_length=100, verbose_name='Верхній заголовок')),
                ('title', models.CharField(max_length=200, verbose_name='Головний заголовок')),
                ('sub_title', models.TextField(blank=True, verbose_name='Під заголовок')),
            ],
            options={
                'verbose_name': 'Сторінка меню',
                'verbose_name_plural': 'Сторінка меню',
            },
        ),
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Номер телефону')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номери',
            },
        ),
        migrations.CreateModel(
            name='WelcomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='welcome/', verbose_name='Зображення')),
                ('item_title', models.CharField(blank=True, max_length=100, verbose_name='Верхній заголовок')),
                ('title', models.CharField(max_length=200, verbose_name='Головний заголовок')),
                ('sub_title', models.TextField(blank=True, verbose_name='Під заголовок')),
            ],
            options={
                'verbose_name': 'Головна сторінка',
                'verbose_name_plural': 'Головна сторінка',
            },
        ),
    ]
